spring:
  application:
    name: STOCK-ORDER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/stockorderservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7171
  servlet:
    context-path: /stock-order-service