spring:
  application:
    name: STOCK-ORDER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/stockorderservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev


server:
  port: 7171
  #servlet:
    #context-path: /stock-order-service


    #hostname: localhost