spring:
  application:
    name: STOCK-SERVICE-API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


server:
  port: 8080


eureka:
  client:
    enabled: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
