spring:
  application:
    name: STOCK-SERVICE-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: C:/Users/anand/OneDrive/Documents/GitHub/Spring-Boot-MicroService-01/git-localconfig-repo

server:
  port: 8888
