spring:
  application:
    name: STOCK-SERVICE-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anandlshinde/git-localconfig-repo
          clone-on-start: true
  profiles:
    active: dev
server:
  port: 8888

