spring:
  application:
    name: STOCK-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/stockservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8181
  #servlet:
    #context-path: /stock-service

eureka:
  instance:
    #hostname: localhost
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      #default-zone: http://localhost:8761/eureka
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}



