spring:
  application:
    name: STOCK-CALCULATION-SERVICE

server:
  port: 8282
  #servlet:
    #context-path: /stock-calculation-service

eureka:
  instance:
    #hostname: localhost
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}


