spring:
  application:
    name: STOCK-CALCULATION-SERVICE
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev

server:
  port: 8282
  #servlet:
    #context-path: /stock-calculation-service


